### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by camhart** [VirgilSecurity/virgil-e3kit-js#115]
**Describe the bug**
I need to modify e3kit to provide multi-card support, so I'm trying to clone the repo and build it as is then extend.  What is needed to build this package(s) properly?  I attempt to do `npm install` and most every command fails.

**To Reproduce**
1. Go to ./packages/e3kit-browser
2. `npm install`
3.  Errors out

```
C:\Users\Cam\projects\virgil-e3kit-js\packages\e3kit-browser>npm install

> @virgilsecurity/e3kit-browser@2.3.0 prepare C:\Users\Cam\projects\virgil-e3kit-js\packages\e3kit-browser
> npm run clean && npm run build


> @virgilsecurity/e3kit-browser@2.3.0 clean C:\Users\Cam\projects\virgil-e3kit-js\packages\e3kit-browser
> rimraf .rpt2_cache dist


> @virgilsecurity/e3kit-browser@2.3.0 build C:\Users\Cam\projects\virgil-e3kit-js\packages\e3kit-browser
> node --max-old-space-size=4096 node_modules/.bin/rollup -c

C:\Users\Cam\projects\virgil-e3kit-js\packages\e3kit-browser\node_modules\.bin\rollup:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @virgilsecurity/e3kit-browser@2.3.0 build: `node --max-old-space-size=4096 node_modules/.bin/rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @virgilsecurity/e3kit-browser@2.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cam\AppData\Roaming\npm-cache\_logs\2020-05-26T19_58_21_972Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @virgilsecurity/e3kit-browser@2.3.0 prepare: `npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @virgilsecurity/e3kit-browser@2.3.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cam\AppData\Roaming\npm-cache\_logs\2020-05-26T19_58_22_008Z-debug.log
```

**Expected behavior**
I'd expect `npm install` to work.

**Desktop (please complete the following information):**
 - OS: Windows 10, node v13.9.0

**Comment by xlwknx** [comment]
Hi @camhart !
We are using yarn workspaces and lerna, so you need to run `yarn install`at the root of the project to install dependecies and link packages.
Also I google this issue, it connected with that is `rollup` bash script is used on windows:
https://github.com/rollup/rollup/issues/1753#issuecomment-346673575

**Comment by camhart** [comment]
Thanks!  Doing it on ubuntu worked.  You should add this to the readme :D.
