### ISSUE TITLE
e3kit-node doesn't run on electron

### ISSUE THREAD

**Issue by camhart** [VirgilSecurity/virgil-e3kit-js#116]
**Describe the bug**
I can't seem to get e3kit-node to run on electron.

```
Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libfoundation.wasm'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at s (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:451)
    at c (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:496)
    at eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:19800)
    at new Promise (<anonymous>) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Cam\\projects\\myapp-desktop\\codename\\dist_electron\\libfoundation.wasm'
}
Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libfoundation.wasm'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at s (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:451)
    at c (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:496)
    at eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:19800)
    at new Promise (<anonymous>) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Cam\\projects\\myapp-desktop\\codename\\dist_electron\\libfoundation.wasm'
}
Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libpythia.wasm'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at a (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:514)
    at i (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:559)
    at eval (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:21974)
    at new Promise (<anonymous>) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Cam\\projects\\myapp-desktop\\codename\\dist_electron\\libpythia.wasm'
}
Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libpythia.wasm'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at a (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:514)
    at i (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:559)
    at eval (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:21974)
    at new Promise (<anonymous>) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Cam\\projects\\myapp-desktop\\codename\\dist_electron\\libpythia.wasm'
}
failed to asynchronously prepare wasm: RuntimeError: abort(Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libfoundation.wasm'). Build with -s ASSERTIONS=1 for more info.
RuntimeError: abort(Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libfoundation.wasm'). Build with -s ASSERTIONS=1 for more info.
    at B (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:2534)
    at eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:19877)
    at new Promise (<anonymous>)
    at n (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:19722)
    at eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:20368)
    at eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:20590)
    at new eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:20596)
    at Dt (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:381812)
    at ModuleInitializer.loadModule (webpack:///./node_modules/@virgilsecurity/init-utils/dist/init-utils.es.js?:77:55)
    at eval (webpack:///./node_modules/@virgilsecurity/init-utils/dist/init-utils.es.js?:95:29)
RuntimeError: abort(Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libfoundation.wasm'). Build with -s ASSERTIONS=1 for more info.
    at B (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:2534)
    at eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:19877)
    at new Promise (<anonymous>)
    at n (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:19722)
    at eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:20368)
    at eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:20590)
    at new eval (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:20596)
    at Dt (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:381812)
    at ModuleInitializer.loadModule (webpack:///./node_modules/@virgilsecurity/init-utils/dist/init-utils.es.js?:77:55)
    at eval (webpack:///./node_modules/@virgilsecurity/init-utils/dist/init-utils.es.js?:95:29)
failed to asynchronously prepare wasm: RuntimeError: abort(Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libpythia.wasm'). Build with -s ASSERTIONS=1 for more info.
RuntimeError: abort(Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libpythia.wasm'). Build with -s ASSERTIONS=1 for more info.
    at U (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:2665)
    at eval (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:22051)
    at new Promise (<anonymous>)
    at r (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:21896)
    at eval (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:22523)
    at eval (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:22745)
    at new r (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:22751)
    at o (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:39995)
    at ModuleInitializer.loadModule (webpack:///./node_modules/@virgilsecurity/init-utils/dist/init-utils.es.js?:77:55)
    at eval (webpack:///./node_modules/@virgilsecurity/init-utils/dist/init-utils.es.js?:95:29)
RuntimeError: abort(Error: ENOENT: no such file or directory, open 'C:\Users\Cam\projects\myapp-desktop\codename\dist_electron\libpythia.wasm'). Build with -s ASSERTIONS=1 for more info.
    at U (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:2665)
    at eval (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:22051)
    at new Promise (<anonymous>)
    at r (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:21896)
    at eval (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:22523)
    at eval (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:22745)
    at new r (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:22751)
    at o (webpack:///./node_modules/@virgilsecurity/core-pythia/node.es.js?:2:39995)
    at ModuleInitializer.loadModule (webpack:///./node_modules/@virgilsecurity/init-utils/dist/init-utils.es.js?:77:55)
    at eval (webpack:///./node_modules/@virgilsecurity/init-utils/dist/init-utils.es.js?:95:29)
```

**To Reproduce**
1. Download Electron Fiddle (https://github.com/electron/fiddle/releases/tag/v0.15.0)
2. Load https://gist.github.com/249c489a30439d2f9ab9911cfe6d6d38 within electron fiddle
3. Add the token callback code in `main.js` line 8

**Expected behavior**
E3kit-node should work

**Desktop (please complete the following information):**
 - OS: Windows 10, 64 bit, electron v8.3.0 w/ electron-builder v22.6.0

**Comment by camhart** [comment]
I believe I found a way to solve this using undocumented initialization options:
```
    this.eThree = await e3kit.EThree.initialize(
      tokenCallback(ds),
      {
        foundationWasmPath: path.join(wasmBasePath, 'libfoundation.wasm'),
        pythiaWasmPath: path.join(wasmBasePath, 'libpythia.wasm')
      }
```
