### ISSUE TITLE
Vite: Rollup failed to resolve import "env" from "node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm".

### ISSUE THREAD

**Issue by marekbednar** [VirgilSecurity/virgil-e3kit-js#150]
I am having the errors using Vite and vite wasm plugin:
```
[vite]: Rollup failed to resolve import "env" from "node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm".
[ERROR] This is most likely unintended because it can break your application at runtime.
```
I am using Vite inside the Vaadin platform, and my vite config is
```
import { UserConfigFn } from 'vite';
import { overrideVaadinConfig } from './vite.generated';
import wasm from "vite-plugin-wasm";
import topLevelAwait from "vite-plugin-top-level-await";

const customConfig: UserConfigFn = (env) => ({
	// Here you can add custom Vite parameters
	// https://vitejs.dev/config/
	plugins: [
		wasm(),
		topLevelAwait()
	],
	server: {
		watch: {
			ignored: ['!**/node_modules/@nordlicht/commons-web-gui-vaadin-v11/**', '!**/node_modules/@vaadin/flow-frontend/**']
		}
	},
	optimizeDeps: {
		exclude: ["@nordlicht/commons-web-gui-vaadin-v11", '@vaadin/flow-frontend'],
		include: ["@virgilsecurity/e3kit-browser", "@virgilsecurity/e3kit-base"]
	},
});

export default overrideVaadinConfig(customConfig);

```

**Comment by x8BitRain** [comment]
I'm also having issues with Vite, it's currently unusable, when using with the WASM import (and ```vite-plugin-wasm```) with:

```js
import { EThree } from '@virgilsecurity/e3kit-browser';
```

Vite outputs:

```
✘ [ERROR] Could not resolve "a"

    vite-plugin-wasm-namespace:/Users/mint/app-frontend/node_modules/@virgilsecurity/e3kit-browser/dist/libpythia.browser.wasm:43:1034:
      43 │ ...as __vite__wasmImport_0_27, C as __vite__wasmImport_0_28, D as __vite__wasmImport_0_29, E as __vite__wasmImport_0_30, F as __vite__wasmImport_0_31, memory as __vite__wasmImport_0_32, table as __vite__wasmImport_0_33 } from "a";
         ╵                                                                                                                                                                                                                                   ~~~

  You can mark the path "a" as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "env"

    vite-plugin-wasm-namespace:/Users/mint/app-frontend/node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm:43:374:
      43 │ ... g as __vite__wasmImport_0_5, h as __vite__wasmImport_0_6, l as __vite__wasmImport_0_7, m as __vite__wasmImport_0_8, n as __vite__wasmImport_0_9, memory as __vite__wasmImport_0_10, table as __vite__wasmImport_0_11 } from "env";
         ╵                                                                                                                                                                                                                                 ~~~~~

  You can mark the path "env" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "wasi_unstable"

    vite-plugin-wasm-namespace:/Users/mint/app-frontend/node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm:44:131:
      44 │ import { e as __vite__wasmImport_1_0, i as __vite__wasmImport_1_1, j as __vite__wasmImport_1_2, k as __vite__wasmImport_1_3 } from "wasi_unstable";
         ╵                                                                                                                                    ~~~~~~~~~~~~~~~

  You can mark the path "wasi_unstable" as external to exclude it from the bundle, which will remove
  this error.


/Users/mint/app-frontend/node_modules/esbuild/lib/main.js:1566
  let error = new Error(`${text}${summary}`);
              ^
Error: Build failed with 3 errors:
vite-plugin-wasm-namespace:/Users/mint/app-frontend/node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm:43:374: ERROR: Could not resolve "env"
vite-plugin-wasm-namespace:/Users/mint/app-frontend/node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm:44:131: ERROR: Could not resolve "wasi_unstable"
vite-plugin-wasm-namespace:/Users/mint/app-frontend/node_modules/@virgilsecurity/e3kit-browser/dist/libpythia.browser.wasm:43:1034: ERROR: Could not resolve "a"
    at failureErrorWithLog (/Users/mint/app-frontend/node_modules/esbuild/lib/main.js:1566:15)
    at /Users/mint/app-frontend/node_modules/esbuild/lib/main.js:1024:28
    at runOnEndCallbacks (/Users/mint/app-frontend/node_modules/esbuild/lib/main.js:1438:61)
    at buildResponseToResult (/Users/mint/app-frontend/node_modules/esbuild/lib/main.js:1022:7)
    at /Users/mint/app-frontend/node_modules/esbuild/lib/main.js:1134:14
    at responseCallbacks.<computed> (/Users/mint/app-frontend/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/Users/mint/app-frontend/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/mint/app-frontend/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
```

If I import ESM asm.js 
(which requires ```vite-plugin-ngmi-polyfill```)

```js
import { EThree } from '@virgilsecurity/e3kit-browser/dist/browser.asmjs.es';
```

I get the following in the browser console when calling ```EThree.initialize()```

```
Uncaught (in promise) RuntimeError: abort(RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at O2 (browser.asmjs.es.js:1:2146)
    at browser.asmjs.es.js:1:21446
```

Can't even get it working with UMD.

index.js:

```html
  <script src="https://unpkg.com/virgil-crypto@^4.2.2/dist/browser.umd.js"></script>
  <script src="https://unpkg.com/virgil-sdk@^6.1.2/dist/virgil-sdk.browser.umd.js"></script>
  <script src="https://unpkg.com/@virgilsecurity/e3kit-browser@^2.5.1/dist/browser.umd.js"></script>
```

In the browser console I get.

```
browser.umd.js:9294 Uncaught ReferenceError: require is not defined
    at browser.umd.js:9294:34
    at browser.umd.js:36:88
    at browser.umd.js:37:3
```

and window.E3kit is just an empty object
{}

I'm on Chrome 108 on M1 mac with Vite 3.2.2

I really want to use E3Kit because it's the only drop in e2e solution I can find but without vite support or even working UMD support this is a deal breaker :(

**Comment by azirb** [comment]
Closing as outdated
