### ISSUE TITLE
Bump @virgilsecurity/pythia-crypto to 2.0.0

### ISSUE THREAD

**Issue by HSCOGT** [VirgilSecurity/virgil-e3kit-js#170]
Using Node 18.19.0, when calling EThree.initialize() I run into the following error.

```
>  TypeError: Failed to parse URL from /usr/src/app/node_modules/@virgilsecurity/core-pythia/libpythia.wasm
>      at Object.fetch (node:internal/deps/undici/undici:11730:11)
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>    [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
>        at new NodeError (node:internal/errors:405:5)
>        at new URL (node:internal/url:676:13)
>        at new Request (node:internal/deps/undici/undici:5270:25)
>        at fetch (node:internal/deps/undici/undici:9508:25)
>        at Object.fetch (node:internal/deps/undici/undici:11728:18)
>        at fetch (node:internal/process/pre_execution:281:25)
>        at /usr/src/app/node_modules/@virgilsecurity/core-pythia/node.cjs.js:1:22469
>        at /usr/src/app/node_modules/@virgilsecurity/core-pythia/node.cjs.js:1:22686
>        at new r (/usr/src/app/node_modules/@virgilsecurity/core-pythia/node.cjs.js:1:22692)
>        at o (/usr/src/app/node_modules/@virgilsecurity/core-pythia/node.cjs.js:1:39936)
>        at ModuleInitializer.loadModule (/usr/src/app/node_modules/@virgilsecurity/init-utils/dist/init-utils.cjs.js:75:55)
>        at /usr/src/app/node_modules/@virgilsecurity/init-utils/dist/init-utils.cjs.js:93:29
>        at Array.map (<anonymous>)
>        at ModuleInitializer.loadModules [as initPythia] (/usr/src/app/node_modules/@virgilsecurity/init-utils/dist/init-utils.cjs.js:89:39)
>        at EThree.initialize (/usr/src/app/node_modules/@virgilsecurity/e3kit-node/dist/node.cjs.js:106:81)
>        at getE3Instance (/usr/src/app/lib/encryption/encryption_utils.js:42:46) {
>      input: '/usr/src/app/node_modules/@virgilsecurity/core-pythia/libpythia.wasm',
>      code: 'ERR_INVALID_URL'
>    }
>  }
```

Similar to: https://github.com/VirgilSecurity/virgil-e3kit-js/issues/166#issue-1964406585, but the other one was caused by 'virgil-crypto' this one is due to 'core-pythia'. The error is fixed on the most recent version 2.0.0.

**Comment by HSCOGT** [comment]
Updating pythia-crypto to 2.0.0 fixed the issue above, but now whenever I try to call EThree.initialize(); it fails and crashes the app without any logs or stack trace of the error. Can someone at Virgil take a look at this, please?

**Comment by rstp-god** [comment]
Hello @HSCOGT ! We updated e3kit for node18+ again, try with 3.0.2 version, if problem still exists tell us back!

**Comment by HSCOGT** [comment]
Hi @rstp-god, I tried running 3.0.2 but I'm getting the original error since the SDK is still using 'pythia-crypto' v1.1.3.

**Comment by rstp-god** [comment]
@HSCOGT Hello! Try new 3.0.5 release, fix all depends!

**Comment by HSCOGT** [comment]
@rstp-god, I'm still getting an error, in either Node 18 or 20, this happens whenever I try to initialize E3.

![Screenshot 2024-01-30 at 16 33 55](https://github.com/VirgilSecurity/virgil-e3kit-js/assets/22054090/caa212e6-01d0-4b58-9979-55a179836b84)

**Comment by HSCOGT** [comment]
@rstp-god Any updates?
