### ISSUE TITLE
Encryption error ReferenceError: Buffer is not defined     at new SubDown (browser.es.js:14144:1)

### ISSUE THREAD

**Issue by thecannabisapp** [VirgilSecurity/virgil-e3kit-js#175]
**Describe the bug**
I'm trying to upgrade my React 18 app using `@virgilsecurity/e3kit-browser": "3.0.5"` coming from v3.0.0 but now I've updated the package, I'm getting the following error when running my application.

```
universalModuleDefinition:1 Encryption error ReferenceError: Buffer is not defined
    at new SubDown (browser.es.js:14144:1)
    at SubDown (browser.es.js:14130:1)
    at module.exports (browser.es.js:15357:1)
    at new GroupLocalStorage (browser.es.js:16926:1)
    at new AbstractEThree (browser.es.js:17065:1)
    at new EThree (browser.es.js:19227:1)
    at initialize (browser.es.js:19258:1)
    at async initializeEncryption (EncryptionProvider.tsx:90:1)
```

Running on `react-app-rewired` here's my `config-overide.js` for reference.

```
// config-overrides.js
const webpack = require("webpack");

module.exports = {
  webpack: function override(config, _env) {
    config.experiments = {
      asyncWebAssembly: true,
      syncWebAssembly: true,
    };
    config.module.rules[
      config.module.rules.findIndex((rule) => rule.oneOf)
    ].oneOf.unshift(
      {
        test: /\.wasm$/,
        type: "javascript/auto",
        loader: "file-loader",
        options: {
          outputPath: "static/wasm/",
        },
      },
      {
        test: /\.(js|mjs|jsx)$/,
        enforce: "pre",
        loader: require.resolve("source-map-loader"),
        resolve: {
          fullySpecified: false,
        },
      }
    );

    // https://github.com/nodejs/readable-stream#usage-in-browsers
    config.plugins.push(
      new webpack.ProvidePlugin({
        process: "process/browser.js",
      })
    );
    config.resolve.fallback = {
      stream: false,
    };

    return config;
  },
};
```

**To Reproduce**
1. Upgrade from v3.0.0 to v3.0.5

**Expected behavior**
No errors in Chrome console.

**Screenshots**
<img width="1333" alt="Screenshot 2024-04-12 at 11 01 03" src="https://github.com/VirgilSecurity/virgil-e3kit-js/assets/58605231/c073a2f5-e0c7-461a-9c21-7fcc339c463b">

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - Version 123.0.6312.123 (Official Build) (x86_64)

**Comment by thecannabisapp** [comment]
Updated to 3.0.6 and edited my config-override.js

```
    config.plugins.push(
      new webpack.ProvidePlugin({
        process: "process/browser.js",
        Buffer: ["buffer", "Buffer"],
      })
    );

    config.resolve.fallback = {
      stream: false,
      buffer: require.resolve("buffer/"),
    };
```
